version: '2'

services:
  nginx:
    image: nginx:1.17
    restart: always
    # Included NGINX config used hostname to determine what it's server_name will be 
    # Either set NGINX_HOSTNAME to it's public DNS name, change this line, or the config
    hostname: localhost
    ports:
      - "443:8443"
    volumes:
      - ./ssl:/etc/ssl:ro # Change this to match where your certificates are. Look at and adjust names in nginx.conf
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - .data/nginx/logs:/var/log/nginx
    networks:
      default:
      internal:
    depends_on:
      - ctfd
